//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LongHu.ObjectModel
{
    [Serializable]
    public class BaseSearchModel
    {
	    public string _sortBy="Id";
        public bool IsAsc { get; set; }
        public string SortBy 
		{ 
		   get{return _sortBy;}
		   set{_sortBy=value;}
		}
		public int PageIndex{get;set;}
    }
    [Serializable]
    public class BaseJsonResultModel
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
    }
}


