//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;
using LongHu.Framework.Resources;

namespace LongHu.ObjectModel
{
    [Serializable]
    public class Department
    {
        #region Primitive Properties
  
        [Key]
        public virtual Decimal Id
        {
            get;
            set;
        }   
			 public virtual string  Name
			{
				get;
				set;
			} 
           public virtual Decimal?  OrgChartId
			{
				get;
				set;
			} 
           public virtual DateTime  CreatedOn
			{
				get;
				set;
			} 
           public virtual Decimal  CreatedByEmployeeId
			{
				get;
				set;
			} 
           public virtual DateTime  ModifiedOn
			{
				get;
				set;
			} 
           public virtual Decimal  ModifiedByEmployeeId
			{
				get;
				set;
			}
           public virtual string IsActive
			{
				get;
				set;
			} 
        public EActionOperationType ActionOperationType { get; set; }

        #endregion
    
        #region Navigation Properties
        public virtual OrgChart  OrgChart
        {
            get;
            set;
        }   
    
              
        public IList<Employee> EmployeeList
        {
            get ;
            set ;
        }
              
        public IList<ProjectPlanCollection> ProjectPlanCollectionList
        {
            get ;
            set ;
        }

        #endregion
    }
	[Serializable]
    public class DepartmentSearch:BaseSearchModel
    {
      public  Decimal?  OrgChartId
        {
            get;
            set;
        }   
	}
}

