
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

namespace LongHu.ObjectModel
{
    public enum EActionOperationType
    {
        Edit = 1,
        Details = 2,
        Delete = 3,
        Create = 4

    }
}

