//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;
using LongHu.Framework.Resources;

namespace LongHu.ObjectModel
{
    [Serializable]
    public class OrgChart
    {
        #region Primitive Properties
  
        [Key]
        public virtual Decimal  Id
        {
            get;
            set;
        }   
			 public virtual string  Name
			{
				get;
				set;
			} 
           public virtual decimal?  ParentId
			{
				get;
				set;
			} 
			 public virtual string  Path
			{
				get;
				set;
			} 
           public virtual DateTime  CreatedOn
			{
				get;
				set;
			} 
           public virtual Decimal  CreatedByEmployeeId
			{
				get;
				set;
			} 
           public virtual DateTime  ModifiedOn
			{
				get;
				set;
			} 
           public virtual Decimal  ModifiedByEmployeeId
			{
				get;
				set;
			} 
           public virtual string   IsActive
			{
				get;
				set;
			} 
        public EActionOperationType ActionOperationType { get; set; }

        #endregion
    
        #region Navigation Properties
    
              
        public IList<Department> DepartmentList
        {
            get ;
            set ;
        }
              
        public IList<EmployeeOrgChart> EmployeeOrgChartList
        {
            get ;
            set ;
        }
              
        public IList<ProjectPlan> ProjectPlanList
        {
            get ;
            set ;
        }
              
        public IList<ProjectPlanCollection> ProjectPlanCollectionList
        {
            get ;
            set ;
        }
              
        public IList<ProjectStructure> ProjectStructureList
        {
            get ;
            set ;
        }

        #endregion
    }
	[Serializable]
    public class OrgChartSearch:BaseSearchModel
    {
	}
}

