//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;
using LongHu.Framework.Resources;

namespace LongHu.ObjectModel
{
    [Serializable]
    public class ProjectPlanCollection
    {
        #region Primitive Properties
  
        [Key]
        public virtual Decimal  Id
        {
            get;
            set;
        }   
           public virtual decimal?  Year
			{
				get;
				set;
			} 
			 public virtual string  AgreementNumber
			{
				get;
				set;
			} 
			 public virtual string  Unit
			{
				get;
				set;
			} 
           public virtual decimal?  Number
			{
				get;
				set;
			} 
           public virtual decimal?  UnitPrice
			{
				get;
				set;
			} 
           public virtual decimal?  EstimateValue
			{
				get;
				set;
			} 
			 public virtual string  QualityRequirement
			{
				get;
				set;
			} 
           public virtual DateTime?  ReviewTime
			{
				get;
				set;
			} 
           public virtual DateTime?  DrawingProvidedTime
			{
				get;
				set;
			} 
           public virtual DateTime?  ContractTime
			{
				get;
				set;
			} 
           public virtual DateTime?  BidStartedTime
			{
				get;
				set;
			} 
           public virtual DateTime?  BidSeningTime
			{
				get;
				set;
			} 
           public virtual DateTime?  BidReturnTime
			{
				get;
				set;
			} 
           public virtual DateTime?  BidCheckTime
			{
				get;
				set;
			} 
           public virtual DateTime?  ContractSignTime
			{
				get;
				set;
			} 
           public virtual DateTime?  ComingIntoTime
			{
				get;
				set;
			} 
			 public virtual string  Comments
			{
				get;
				set;
			} 
           public virtual DateTime  CreatedOn
			{
				get;
				set;
			} 
           public virtual Decimal  CreatedByEmployeeId
			{
				get;
				set;
			} 
           public virtual DateTime  ModifiedOn
			{
				get;
				set;
			} 
           public virtual Decimal  ModifiedByEmployeeId
			{
				get;
				set;
			} 
           public virtual Decimal?  ProjectPlanId
			{
				get;
				set;
			} 
           public virtual Decimal?  ContractId
			{
				get;
				set;
			} 
           public virtual Decimal?  OrgChartId
			{
				get;
				set;
			} 
           public virtual Decimal?  BidTypeId
			{
				get;
				set;
			} 
           public virtual Decimal?  DepartmentId
			{
				get;
				set;
			} 
           public virtual Decimal?  ResearchOwnerEmployeeId
			{
				get;
				set;
			} 
           public virtual Decimal?  EngeerEmployeeId
			{
				get;
				set;
			} 
           public virtual Decimal?  CostOwnerEmployeeId
			{
				get;
				set;
			} 
           public virtual Decimal?  AuthorEmployeeId
			{
				get;
				set;
			} 
           public virtual Decimal?  OrganizerEmployeeId
			{
				get;
				set;
			}
           public virtual string IsActive
			{
				get;
				set;
			} 
        public EActionOperationType ActionOperationType { get; set; }

        #endregion
    
        #region Navigation Properties
        public virtual ProjectPlan  ProjectPlan
        {
            get;
            set;
        }   
        public virtual Contract  Contract
        {
            get;
            set;
        }   
        public virtual OrgChart  OrgChart
        {
            get;
            set;
        }   
        public virtual DataDictionary  DataDictionary
        {
            get;
            set;
        }   
        public virtual Department  Department
        {
            get;
            set;
        }   
        public virtual Employee  Employee
        {
            get;
            set;
        }   
       
    

        #endregion
    }
	[Serializable]
    public class ProjectPlanCollectionSearch:BaseSearchModel
    {
      public  Decimal?  ProjectPlanId
        {
            get;
            set;
        }   
      public  Decimal?  ContractId
        {
            get;
            set;
        }   
      public  Decimal?  OrgChartId
        {
            get;
            set;
        }   
      public  Decimal?  BidTypeId
        {
            get;
            set;
        }   
      public  Decimal?  DepartmentId
        {
            get;
            set;
        }   
      public  Decimal?  ResearchOwnerEmployeeId
        {
            get;
            set;
        }   
      public  Decimal?  EngeerEmployeeId
        {
            get;
            set;
        }   
      public  Decimal?  CostOwnerEmployeeId
        {
            get;
            set;
        }   
      public  Decimal?  AuthorEmployeeId
        {
            get;
            set;
        }   
      public  Decimal?  OrganizerEmployeeId
        {
            get;
            set;
        }   
	}
}

