//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;
using LongHu.Framework.Resources;

namespace LongHu.ObjectModel
{
    [Serializable]
    public class ProjectPlan
    {
        #region Primitive Properties
  
        [Key]
        public virtual Decimal Id
        {
            get;
            set;
        }   
			 public virtual string  ProjectName
			{
				get;
				set;
			} 
			 public virtual string  BidPlanNumber
			{
				get;
				set;
			} 
			 public virtual string  Description
			{
				get;
				set;
			} 
           public virtual DateTime  CreatedOn
			{
				get;
				set;
			} 
           public virtual Decimal  CreatedByEmployeeId
			{
				get;
				set;
			} 
           public virtual DateTime  ModifiedOn
			{
				get;
				set;
			} 
           public virtual Decimal  ModifiedByEmployeeId
			{
				get;
				set;
			} 
			 public virtual string  VersionName
			{
				get;
				set;
			} 
           public virtual Decimal?  Version
			{
				get;
				set;
			} 
           public virtual decimal?  IsForYear
			{
				get;
				set;
			} 
        [Required(ErrorMessageResourceName="ValidationMessageProjectStructureNameRequired", ErrorMessageResourceType=typeof(ProjectPlanResources))]
        public virtual Decimal  ProjectStructureId
        {
            get;
            set;
        }   
        [Required(ErrorMessageResourceName="ValidationMessageOrgChartNameRequired", ErrorMessageResourceType=typeof(ProjectPlanResources))]
        public virtual Decimal  OrgChartId
        {
            get;
            set;
        }   
           public virtual Decimal?  AuthorEmployeeId
			{
				get;
				set;
			}
           public virtual string IsActive
			{
				get;
				set;
			} 
           public virtual DateTime?  OperatedOn
			{
				get;
				set;
			} 
        [Required(ErrorMessageResourceName="ValidationMessageEmployeeNameRequired", ErrorMessageResourceType=typeof(ProjectPlanResources))]
        public virtual Decimal  OperatedByEmployeeId
        {
            get;
            set;
        }   
        [Required(ErrorMessageResourceName="ValidationMessageDataDictionaryNameRequired", ErrorMessageResourceType=typeof(ProjectPlanResources))]
        public virtual Decimal  ProjectPlanInformationStatusId
        {
            get;
            set;
        }   
        public EActionOperationType ActionOperationType { get; set; }

        #endregion
    
        #region Navigation Properties
        public virtual ProjectStructure  ProjectStructure
        {
            get;
            set;
        }   
        public virtual OrgChart  OrgChart
        {
            get;
            set;
        }   
        public virtual Employee  Employee
        {
            get;
            set;
        }   
        
        public virtual DataDictionary  DataDictionary
        {
            get;
            set;
        }   
    
              
        public IList<ProjectPlanCollection> ProjectPlanCollectionList
        {
            get ;
            set ;
        }

        #endregion
    }
	[Serializable]
    public class ProjectPlanSearch:BaseSearchModel
    {
      public  Decimal?  ProjectStructureId
        {
            get;
            set;
        }   
      public  Decimal?  OrgChartId
        {
            get;
            set;
        }   
      public  Decimal?  AuthorEmployeeId
        {
            get;
            set;
        }   
      public  Decimal?  OperatedByEmployeeId
        {
            get;
            set;
        }   
      public  Decimal?  ProjectPlanInformationStatusId
        {
            get;
            set;
        }   
	}
}

