//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongHu.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectPlanCollectionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectPlanCollectionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LongHu.Framework.Resources.ProjectPlanCollectionResources", typeof(ProjectPlanCollectionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ProjectPlanCollection.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating ProjectPlanCollection.
        /// </summary>
        public static string CreateValidationSummaryMessage {
            get {
                return ResourceManager.GetString("CreateValidationSummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this ProjectPlanCollection?.
        /// </summary>
        public static string DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ProjectPlanCollection.
        /// </summary>
        public static string DeletePageTitle {
            get {
                return ResourceManager.GetString("DeletePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPlanCollection Details.
        /// </summary>
        public static string DetailsPageTitle {
            get {
                return ResourceManager.GetString("DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ProjectPlanCollection.
        /// </summary>
        public static string EditPageTitle {
            get {
                return ResourceManager.GetString("EditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating ProjectPlanCollection.
        /// </summary>
        public static string EditValidationSummaryMessage {
            get {
                return ResourceManager.GetString("EditValidationSummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPlanCollection List.
        /// </summary>
        public static string ListPageTitle {
            get {
                return ResourceManager.GetString("ListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPlanCollection.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string LabelYear {
            get {
                return ResourceManager.GetString("LabelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgreementNumber.
        /// </summary>
        public static string LabelAgreementNumber {
            get {
                return ResourceManager.GetString("LabelAgreementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string LabelUnit {
            get {
                return ResourceManager.GetString("LabelUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string LabelNumber {
            get {
                return ResourceManager.GetString("LabelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice.
        /// </summary>
        public static string LabelUnitPrice {
            get {
                return ResourceManager.GetString("LabelUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstimateValue.
        /// </summary>
        public static string LabelEstimateValue {
            get {
                return ResourceManager.GetString("LabelEstimateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualityRequirement.
        /// </summary>
        public static string LabelQualityRequirement {
            get {
                return ResourceManager.GetString("LabelQualityRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReviewTime.
        /// </summary>
        public static string LabelReviewTime {
            get {
                return ResourceManager.GetString("LabelReviewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrawingProvidedTime.
        /// </summary>
        public static string LabelDrawingProvidedTime {
            get {
                return ResourceManager.GetString("LabelDrawingProvidedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractTime.
        /// </summary>
        public static string LabelContractTime {
            get {
                return ResourceManager.GetString("LabelContractTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BidStartedTime.
        /// </summary>
        public static string LabelBidStartedTime {
            get {
                return ResourceManager.GetString("LabelBidStartedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BidSeningTime.
        /// </summary>
        public static string LabelBidSeningTime {
            get {
                return ResourceManager.GetString("LabelBidSeningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BidReturnTime.
        /// </summary>
        public static string LabelBidReturnTime {
            get {
                return ResourceManager.GetString("LabelBidReturnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BidCheckTime.
        /// </summary>
        public static string LabelBidCheckTime {
            get {
                return ResourceManager.GetString("LabelBidCheckTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractSignTime.
        /// </summary>
        public static string LabelContractSignTime {
            get {
                return ResourceManager.GetString("LabelContractSignTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComingIntoTime.
        /// </summary>
        public static string LabelComingIntoTime {
            get {
                return ResourceManager.GetString("LabelComingIntoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string LabelComments {
            get {
                return ResourceManager.GetString("LabelComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedOn.
        /// </summary>
        public static string LabelCreatedOn {
            get {
                return ResourceManager.GetString("LabelCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedOn.
        /// </summary>
        public static string LabelModifiedOn {
            get {
                return ResourceManager.GetString("LabelModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPlan Name.
        /// </summary>
        public static string LabelProjectPlanId {
            get {
                return ResourceManager.GetString("LabelProjectPlanId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contract Name.
        /// </summary>
        public static string LabelContractId {
            get {
                return ResourceManager.GetString("LabelContractId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OrgChart Name.
        /// </summary>
        public static string LabelOrgChartId {
            get {
                return ResourceManager.GetString("LabelOrgChartId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataDictionary Name.
        /// </summary>
        public static string LabelBidTypeId {
            get {
                return ResourceManager.GetString("LabelBidTypeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string LabelDepartmentId {
            get {
                return ResourceManager.GetString("LabelDepartmentId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string LabelResearchOwnerEmployeeId {
            get {
                return ResourceManager.GetString("LabelResearchOwnerEmployeeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string LabelEngeerEmployeeId {
            get {
                return ResourceManager.GetString("LabelEngeerEmployeeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string LabelCostOwnerEmployeeId {
            get {
                return ResourceManager.GetString("LabelCostOwnerEmployeeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string LabelAuthorEmployeeId {
            get {
                return ResourceManager.GetString("LabelAuthorEmployeeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string LabelOrganizerEmployeeId {
            get {
                return ResourceManager.GetString("LabelOrganizerEmployeeId", resourceCulture);
            }
        }

   
    }
}

