//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongHu.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectPlanResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectPlanResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LongHu.Framework.Resources.ProjectPlanResources", typeof(ProjectPlanResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ProjectPlan.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating ProjectPlan.
        /// </summary>
        public static string CreateValidationSummaryMessage {
            get {
                return ResourceManager.GetString("CreateValidationSummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this ProjectPlan?.
        /// </summary>
        public static string DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ProjectPlan.
        /// </summary>
        public static string DeletePageTitle {
            get {
                return ResourceManager.GetString("DeletePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPlan Details.
        /// </summary>
        public static string DetailsPageTitle {
            get {
                return ResourceManager.GetString("DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ProjectPlan.
        /// </summary>
        public static string EditPageTitle {
            get {
                return ResourceManager.GetString("EditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating ProjectPlan.
        /// </summary>
        public static string EditValidationSummaryMessage {
            get {
                return ResourceManager.GetString("EditValidationSummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPlan List.
        /// </summary>
        public static string ListPageTitle {
            get {
                return ResourceManager.GetString("ListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPlan.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProjectName.
        /// </summary>
        public static string LabelProjectName {
            get {
                return ResourceManager.GetString("LabelProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BidPlanNumber.
        /// </summary>
        public static string LabelBidPlanNumber {
            get {
                return ResourceManager.GetString("LabelBidPlanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedOn.
        /// </summary>
        public static string LabelCreatedOn {
            get {
                return ResourceManager.GetString("LabelCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedOn.
        /// </summary>
        public static string LabelModifiedOn {
            get {
                return ResourceManager.GetString("LabelModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionName.
        /// </summary>
        public static string LabelVersionName {
            get {
                return ResourceManager.GetString("LabelVersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsForYear.
        /// </summary>
        public static string LabelIsForYear {
            get {
                return ResourceManager.GetString("LabelIsForYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectStructureName is required.
        /// </summary>
        public static string ValidationMessageProjectStructureNameRequired {
            get {
                return ResourceManager.GetString("ValidationMessageProjectStructureNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProjectStructureName.
        /// </summary>
        public static string LabelProjectStructureId {
            get {
                return ResourceManager.GetString("LabelProjectStructureId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OrgChartName is required.
        /// </summary>
        public static string ValidationMessageOrgChartNameRequired {
            get {
                return ResourceManager.GetString("ValidationMessageOrgChartNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OrgChartName.
        /// </summary>
        public static string LabelOrgChartId {
            get {
                return ResourceManager.GetString("LabelOrgChartId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string LabelAuthorEmployeeId {
            get {
                return ResourceManager.GetString("LabelAuthorEmployeeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OperatedOn.
        /// </summary>
        public static string LabelOperatedOn {
            get {
                return ResourceManager.GetString("LabelOperatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeName is required.
        /// </summary>
        public static string ValidationMessageEmployeeNameRequired {
            get {
                return ResourceManager.GetString("ValidationMessageEmployeeNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmployeeName.
        /// </summary>
        public static string LabelOperatedByEmployeeId {
            get {
                return ResourceManager.GetString("LabelOperatedByEmployeeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataDictionaryName is required.
        /// </summary>
        public static string ValidationMessageDataDictionaryNameRequired {
            get {
                return ResourceManager.GetString("ValidationMessageDataDictionaryNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataDictionaryName.
        /// </summary>
        public static string LabelProjectPlanInformationStatusId {
            get {
                return ResourceManager.GetString("LabelProjectPlanInformationStatusId", resourceCulture);
            }
        }

   
    }
}

