//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

using LongHu.DataAccess;
using LongHu.Framework;
using LongHu.Framework.Utility;
using System.Linq.Expressions;
using System;
using My.FrameWork.Utilities;
using My.FrameWork.Utilities.Cache;

namespace LongHu.BusinessLogic
{
    public class ContractService
    {
        #region Save method
        /// <summary>
        ///  save Entity Method
        /// </summary>
        /// <param name="svarContract"></param>
        public Decimal Add(ObjectModel.Contract svarContract)
        {
		    svarContract.IsActive = "1";
            var rmodel = new ConvertModel();
            var sContract = rmodel.ReturnModel<Contract, ObjectModel.Contract>(svarContract);
            var dao = new ContractRepository();
            var newItem=dao.Insert(sContract);
			return newItem.Id;
        }

        #endregion

        #region Update method
        /// <summary>
        ///  Edit Entity Method
        /// </summary>
        /// <param name="evarContract"></param>
        public void Update(ObjectModel.Contract evarContract)
        {
            var rmodel = new ConvertModel();
            var eContract = rmodel.ReturnModel<Contract, ObjectModel.Contract>(evarContract);
            var dao = new ContractRepository();
            var dataContract = dao.Query(s => s.Id == evarContract.Id).FirstOrDefault();
            //eContract.CreatedOn =dataContract.CreatedOn;
            //eContract.CreatedByEmployeeId =dataContract.CreatedByEmployeeId;
            //eContract.ModifiedByEmployeeId =ConstantManager.GetCurrentUserId();
            //eContract.ModifiedOn =DateTime.Now;
    		eContract.IsActive =dataContract.IsActive;
            dao.Update(eContract, c => c.Id == eContract.Id);

        }

        #endregion

        #region Remove method
        /// <summary>
        ///  Delete Entity Method
        /// </summary>
        /// <param name="dvarContract"></param>    
        public void Remove(ObjectModel.Contract dvarContract)
        {
            var dao = new ContractRepository();
            dao.Delete(s => s.Id == dvarContract.Id);
        }

        #endregion

        #region Get Single
        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelContract"></param>
        /// <returns></returns>
        public ObjectModel.Contract GetContractByID(ObjectModel.Contract modelContract)
        {
            var rmodel = new ConvertModel();
            var dao = new ContractRepository();
            var dataContract = dao.Query(s => s.Id == modelContract.Id).FirstOrDefault();

            return rmodel.ReturnModel<ObjectModel.Contract, Contract>(dataContract);
        }

        #endregion

        #region Get Query
        /// <summary>
        ///  Get Entity List 
        /// </summary>
        /// <returns>List</returns>
        public IList<ObjectModel.Contract> FindAll()
        {
            var rmodel = new ConvertModel();
            var list = new List<ObjectModel.Contract>();
            var daContract = new ContractRepository();
            foreach (var vartemp in daContract.Query(c => c.IsActive == "1"))
            {
                var omContract = rmodel.ReturnModel<ObjectModel.Contract, Contract>(vartemp);
                list.Add(omContract);
            }
            return list;
        }

        #endregion

        #region Get Page Query
        /// <summary>
        ///  Get Entity Page Query
        /// </summary>
        /// <returns>List</returns>
        public IList<ObjectModel.Contract> QueryByPage<TKey>(Expression<Func<ObjectModel.Contract, bool>> filter, Expression<Func<ObjectModel.Contract, TKey>> orderBy, int orderType, int pageSize, int pageIndex, out int recordsCount)
        {
		    var newFilter = ExpressionConverter<Contract>.Convert(filter);
            var newOrderBy = ExpressionConverter<Contract>.Convert(orderBy);
            var dao = new ContractRepository();
            var rmodel = new ConvertModel();
            var list = new List<ObjectModel.Contract>();
            var dataList= dao.QueryByPage(newFilter, newOrderBy, orderType, pageSize, pageIndex, out recordsCount);
            if (null == dataList) return null;
            foreach (var vartemp in dataList)
            {
                var omContract = rmodel.ReturnModel<ObjectModel.Contract, Contract>(vartemp);
                list.Add(omContract);
            }
            return list;

        }
		private IList<ObjectModel.Contract> QueryData(Expression<Func<Contract, bool>> filter, Expression<Func<Contract, ObjectModel.Contract>> selector)
        {
             var newfilter = ExpressionConverter<Contract>.Convert(filter);
            var dao = new ContractRepository();
         
            var dataList = dao.Query(newfilter, p => new ObjectModel.Contract { 
            //write something
            }).ToList();
            return dataList;
        }
        public IList<ObjectModel.Contract> Query(Expression<Func<ObjectModel.Contract, bool>> filter)
        {
		    var newfilter = ExpressionConverter<Contract>.Convert(filter);
            var dao = new ContractRepository();
            var rmodel = new ConvertModel();
            var list = new List<ObjectModel.Contract>();
            var dataList = dao.Query(newfilter).ToList();
            if (null == dataList) return null;
            foreach (var vartemp in dataList)
            {
                var omContract = rmodel.ReturnModel<ObjectModel.Contract, Contract>(vartemp);
                list.Add(omContract);
            }
            return list;
        }

		public IList<ObjectModel.Contract> QueryByPage(Expression<Func<ObjectModel.Contract, bool>> filter, string orderBy, int pageSize, int pageIndex, out int recordsCount)
        {         
            var newfilter = ExpressionConverter<Contract>.Convert(filter);
			var dao = new ContractRepository();
            var dataList = dao.QueryByPage(newfilter, orderBy, pageSize, pageIndex, out recordsCount).ToList();           
            if (null == dataList) return null;
            var list = new List<ObjectModel.Contract>();
            var rmodel = new ConvertModel();
            foreach (var vartemp in dataList)
            {
                var omContract = rmodel.ReturnModel<ObjectModel.Contract, Contract>(vartemp);
                list.Add(omContract);
            }
            return list;

        }
		public IList<ObjectModel.Contract> GetContractFromCache()
        {
            var key = "Contract_key";
			var query=CacheHelper.Get(key) as IList<ObjectModel.Contract>;
            if (null == query)
            {
                query = this.Query(q => q.IsActive=="1");
				DateTime ExpirationTime = DateTime.Now.AddMinutes(ConstantManager.CacheCurrentUserExpirationTime);
                CacheHelper.Insert(key, query, ExpirationTime);
            }
            return query;
        }
		public ObjectModel.Contract GetSingleOrDefault(Expression<Func<ObjectModel.Contract, bool>> filter, string orderBy)
        {
            var newfilter = ExpressionConverter<Contract>.Convert(filter);
            var dao = new ContractRepository();
            int recordCount = 0;
            var data = dao.QueryByPage(newfilter, orderBy, 1, 1, out recordCount).ToList().FirstOrDefault();
            if (null == data) return null;
            var list = new List<ObjectModel.Contract>();
            var rmodel = new ConvertModel();
            return rmodel.ReturnModel<ObjectModel.Contract, Contract>(data);

        }
        #endregion
    }
}



