//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

using LongHu.DataAccess;
using LongHu.Framework;
using LongHu.Framework.Utility;
using System.Linq.Expressions;
using System;
using My.FrameWork.Utilities;
using My.FrameWork.Utilities.Cache;

namespace LongHu.BusinessLogic
{
    public class ProjectPlanService
    {
        #region Save method
        /// <summary>
        ///  save Entity Method
        /// </summary>
        /// <param name="svarProjectPlan"></param>
        public Decimal Add(ObjectModel.ProjectPlan svarProjectPlan)
        {
		    svarProjectPlan.IsActive = "1";
            var rmodel = new ConvertModel();
            var sProjectPlan = rmodel.ReturnModel<ProjectPlan, ObjectModel.ProjectPlan>(svarProjectPlan);
            var dao = new ProjectPlanRepository();
            var newItem=dao.Insert(sProjectPlan);
			return newItem.Id;
        }

        #endregion

        #region Update method
        /// <summary>
        ///  Edit Entity Method
        /// </summary>
        /// <param name="evarProjectPlan"></param>
        public void Update(ObjectModel.ProjectPlan evarProjectPlan)
        {
            var rmodel = new ConvertModel();
            var eProjectPlan = rmodel.ReturnModel<ProjectPlan, ObjectModel.ProjectPlan>(evarProjectPlan);
            var dao = new ProjectPlanRepository();
            var dataProjectPlan = dao.Query(s => s.Id == evarProjectPlan.Id).FirstOrDefault();
            //eProjectPlan.CreatedOn =dataProjectPlan.CreatedOn;
            //eProjectPlan.CreatedByEmployeeId =dataProjectPlan.CreatedByEmployeeId;
            //eProjectPlan.ModifiedByEmployeeId =ConstantManager.GetCurrentUserId();
            //eProjectPlan.ModifiedOn =DateTime.Now;
    		eProjectPlan.IsActive =dataProjectPlan.IsActive;
            dao.Update(eProjectPlan, c => c.Id == eProjectPlan.Id);

        }

        #endregion

        #region Remove method
        /// <summary>
        ///  Delete Entity Method
        /// </summary>
        /// <param name="dvarProjectPlan"></param>    
        public void Remove(ObjectModel.ProjectPlan dvarProjectPlan)
        {
            var dao = new ProjectPlanRepository();
            dao.Delete(s => s.Id == dvarProjectPlan.Id);
        }

        #endregion

        #region Get Single
        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelProjectPlan"></param>
        /// <returns></returns>
        public ObjectModel.ProjectPlan GetProjectPlanByID(ObjectModel.ProjectPlan modelProjectPlan)
        {
            var rmodel = new ConvertModel();
            var dao = new ProjectPlanRepository();
            var dataProjectPlan = dao.Query(s => s.Id == modelProjectPlan.Id).FirstOrDefault();

            return rmodel.ReturnModel<ObjectModel.ProjectPlan, ProjectPlan>(dataProjectPlan);
        }

        #endregion

        #region Get Query
        /// <summary>
        ///  Get Entity List 
        /// </summary>
        /// <returns>List</returns>
        public IList<ObjectModel.ProjectPlan> FindAll()
        {
            var rmodel = new ConvertModel();
            var list = new List<ObjectModel.ProjectPlan>();
            var daProjectPlan = new ProjectPlanRepository();
            foreach (var vartemp in daProjectPlan.Query(c => c.IsActive == "1"))
            {
                var omProjectPlan = rmodel.ReturnModel<ObjectModel.ProjectPlan, ProjectPlan>(vartemp);
                list.Add(omProjectPlan);
            }
            return list;
        }

        #endregion

        #region Get Page Query
        /// <summary>
        ///  Get Entity Page Query
        /// </summary>
        /// <returns>List</returns>
        public IList<ObjectModel.ProjectPlan> QueryByPage<TKey>(Expression<Func<ObjectModel.ProjectPlan, bool>> filter, Expression<Func<ObjectModel.ProjectPlan, TKey>> orderBy, int orderType, int pageSize, int pageIndex, out int recordsCount)
        {
		    var newFilter = ExpressionConverter<ProjectPlan>.Convert(filter);
            var newOrderBy = ExpressionConverter<ProjectPlan>.Convert(orderBy);
            var dao = new ProjectPlanRepository();
            var rmodel = new ConvertModel();
            var list = new List<ObjectModel.ProjectPlan>();
            var dataList= dao.QueryByPage(newFilter, newOrderBy, orderType, pageSize, pageIndex, out recordsCount);
            if (null == dataList) return null;
            foreach (var vartemp in dataList)
            {
                var omProjectPlan = rmodel.ReturnModel<ObjectModel.ProjectPlan, ProjectPlan>(vartemp);
                list.Add(omProjectPlan);
            }
            return list;

        }
		private IList<ObjectModel.ProjectPlan> QueryData(Expression<Func<ProjectPlan, bool>> filter, Expression<Func<ProjectPlan, ObjectModel.ProjectPlan>> selector)
        {
             var newfilter = ExpressionConverter<ProjectPlan>.Convert(filter);
            var dao = new ProjectPlanRepository();
         
            var dataList = dao.Query(newfilter, p => new ObjectModel.ProjectPlan { 
            //write something
            }).ToList();
            return dataList;
        }
        public IList<ObjectModel.ProjectPlan> Query(Expression<Func<ObjectModel.ProjectPlan, bool>> filter)
        {
		    var newfilter = ExpressionConverter<ProjectPlan>.Convert(filter);
            var dao = new ProjectPlanRepository();
            var rmodel = new ConvertModel();
            var list = new List<ObjectModel.ProjectPlan>();
            var dataList = dao.Query(newfilter).ToList();
            if (null == dataList) return null;
            foreach (var vartemp in dataList)
            {
                var omProjectPlan = rmodel.ReturnModel<ObjectModel.ProjectPlan, ProjectPlan>(vartemp);
                list.Add(omProjectPlan);
            }
            return list;
        }

		public IList<ObjectModel.ProjectPlan> QueryByPage(Expression<Func<ObjectModel.ProjectPlan, bool>> filter, string orderBy, int pageSize, int pageIndex, out int recordsCount)
        {         
            var newfilter = ExpressionConverter<ProjectPlan>.Convert(filter);
			var dao = new ProjectPlanRepository();
            var dataList = dao.QueryByPage(newfilter, orderBy, pageSize, pageIndex, out recordsCount).ToList();           
            if (null == dataList) return null;
            var list = new List<ObjectModel.ProjectPlan>();
            var rmodel = new ConvertModel();
            foreach (var vartemp in dataList)
            {
                var omProjectPlan = rmodel.ReturnModel<ObjectModel.ProjectPlan, ProjectPlan>(vartemp);
                list.Add(omProjectPlan);
            }
            return list;

        }
		public IList<ObjectModel.ProjectPlan> GetProjectPlanFromCache()
        {
            var key = "ProjectPlan_key";
			var query=CacheHelper.Get(key) as IList<ObjectModel.ProjectPlan>;
            if (null == query)
            {
                query = this.Query(q => q.IsActive=="1");
				DateTime ExpirationTime = DateTime.Now.AddMinutes(ConstantManager.CacheCurrentUserExpirationTime);
                CacheHelper.Insert(key, query, ExpirationTime);
            }
            return query;
        }
		public ObjectModel.ProjectPlan GetSingleOrDefault(Expression<Func<ObjectModel.ProjectPlan, bool>> filter, string orderBy)
        {
            var newfilter = ExpressionConverter<ProjectPlan>.Convert(filter);
            var dao = new ProjectPlanRepository();
            int recordCount = 0;
            var data = dao.QueryByPage(newfilter, orderBy, 1, 1, out recordCount).ToList().FirstOrDefault();
            if (null == data) return null;
            var list = new List<ObjectModel.ProjectPlan>();
            var rmodel = new ConvertModel();
            return rmodel.ReturnModel<ObjectModel.ProjectPlan, ProjectPlan>(data);

        }
        #endregion
    }
}



