//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

using LongHu.DataAccess;
using LongHu.Framework;
using LongHu.Framework.Utility;
using System.Linq.Expressions;
using System;
using My.FrameWork.Utilities;
using My.FrameWork.Utilities.Cache;

namespace LongHu.BusinessLogic
{
    public class ProjectPlanCollectionService
    {
        #region Save method
        /// <summary>
        ///  save Entity Method
        /// </summary>
        /// <param name="svarProjectPlanCollection"></param>
        public Decimal Add(ObjectModel.ProjectPlanCollection svarProjectPlanCollection)
        {
		    svarProjectPlanCollection.IsActive = "1";
            var rmodel = new ConvertModel();
            var sProjectPlanCollection = rmodel.ReturnModel<ProjectPlanCollection, ObjectModel.ProjectPlanCollection>(svarProjectPlanCollection);
            var dao = new ProjectPlanCollectionRepository();
            var newItem=dao.Insert(sProjectPlanCollection);
			return newItem.Id;
        }

        #endregion

        #region Update method
        /// <summary>
        ///  Edit Entity Method
        /// </summary>
        /// <param name="evarProjectPlanCollection"></param>
        public void Update(ObjectModel.ProjectPlanCollection evarProjectPlanCollection)
        {
            var rmodel = new ConvertModel();
            var eProjectPlanCollection = rmodel.ReturnModel<ProjectPlanCollection, ObjectModel.ProjectPlanCollection>(evarProjectPlanCollection);
            var dao = new ProjectPlanCollectionRepository();
            var dataProjectPlanCollection = dao.Query(s => s.Id == evarProjectPlanCollection.Id).FirstOrDefault();
            //eProjectPlanCollection.CreatedOn =dataProjectPlanCollection.CreatedOn;
            //eProjectPlanCollection.CreatedByEmployeeId =dataProjectPlanCollection.CreatedByEmployeeId;
            //eProjectPlanCollection.ModifiedByEmployeeId =ConstantManager.GetCurrentUserId();
            //eProjectPlanCollection.ModifiedOn =DateTime.Now;
    		eProjectPlanCollection.IsActive =dataProjectPlanCollection.IsActive;
            dao.Update(eProjectPlanCollection, c => c.Id == eProjectPlanCollection.Id);

        }

        #endregion

        #region Remove method
        /// <summary>
        ///  Delete Entity Method
        /// </summary>
        /// <param name="dvarProjectPlanCollection"></param>    
        public void Remove(ObjectModel.ProjectPlanCollection dvarProjectPlanCollection)
        {
            var dao = new ProjectPlanCollectionRepository();
            dao.Delete(s => s.Id == dvarProjectPlanCollection.Id);
        }

        #endregion

        #region Get Single
        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelProjectPlanCollection"></param>
        /// <returns></returns>
        public ObjectModel.ProjectPlanCollection GetProjectPlanCollectionByID(ObjectModel.ProjectPlanCollection modelProjectPlanCollection)
        {
            var rmodel = new ConvertModel();
            var dao = new ProjectPlanCollectionRepository();
            var dataProjectPlanCollection = dao.Query(s => s.Id == modelProjectPlanCollection.Id).FirstOrDefault();

            return rmodel.ReturnModel<ObjectModel.ProjectPlanCollection, ProjectPlanCollection>(dataProjectPlanCollection);
        }

        #endregion

        #region Get Query
        /// <summary>
        ///  Get Entity List 
        /// </summary>
        /// <returns>List</returns>
        public IList<ObjectModel.ProjectPlanCollection> FindAll()
        {
            var rmodel = new ConvertModel();
            var list = new List<ObjectModel.ProjectPlanCollection>();
            var daProjectPlanCollection = new ProjectPlanCollectionRepository();
            foreach (var vartemp in daProjectPlanCollection.Query(c => c.IsActive == "1"))
            {
                var omProjectPlanCollection = rmodel.ReturnModel<ObjectModel.ProjectPlanCollection, ProjectPlanCollection>(vartemp);
                list.Add(omProjectPlanCollection);
            }
            return list;
        }

        #endregion

        #region Get Page Query
        /// <summary>
        ///  Get Entity Page Query
        /// </summary>
        /// <returns>List</returns>
        public IList<ObjectModel.ProjectPlanCollection> QueryByPage<TKey>(Expression<Func<ObjectModel.ProjectPlanCollection, bool>> filter, Expression<Func<ObjectModel.ProjectPlanCollection, TKey>> orderBy, int orderType, int pageSize, int pageIndex, out int recordsCount)
        {
		    var newFilter = ExpressionConverter<ProjectPlanCollection>.Convert(filter);
            var newOrderBy = ExpressionConverter<ProjectPlanCollection>.Convert(orderBy);
            var dao = new ProjectPlanCollectionRepository();
            var rmodel = new ConvertModel();
            var list = new List<ObjectModel.ProjectPlanCollection>();
            var dataList= dao.QueryByPage(newFilter, newOrderBy, orderType, pageSize, pageIndex, out recordsCount);
            if (null == dataList) return null;
            foreach (var vartemp in dataList)
            {
                var omProjectPlanCollection = rmodel.ReturnModel<ObjectModel.ProjectPlanCollection, ProjectPlanCollection>(vartemp);
                list.Add(omProjectPlanCollection);
            }
            return list;

        }
		private IList<ObjectModel.ProjectPlanCollection> QueryData(Expression<Func<ProjectPlanCollection, bool>> filter, Expression<Func<ProjectPlanCollection, ObjectModel.ProjectPlanCollection>> selector)
        {
             var newfilter = ExpressionConverter<ProjectPlanCollection>.Convert(filter);
            var dao = new ProjectPlanCollectionRepository();
         
            var dataList = dao.Query(newfilter, p => new ObjectModel.ProjectPlanCollection { 
            //write something
            }).ToList();
            return dataList;
        }
        public IList<ObjectModel.ProjectPlanCollection> Query(Expression<Func<ObjectModel.ProjectPlanCollection, bool>> filter)
        {
		    var newfilter = ExpressionConverter<ProjectPlanCollection>.Convert(filter);
            var dao = new ProjectPlanCollectionRepository();
            var rmodel = new ConvertModel();
            var list = new List<ObjectModel.ProjectPlanCollection>();
            var dataList = dao.Query(newfilter).ToList();
            if (null == dataList) return null;
            foreach (var vartemp in dataList)
            {
                var omProjectPlanCollection = rmodel.ReturnModel<ObjectModel.ProjectPlanCollection, ProjectPlanCollection>(vartemp);
                list.Add(omProjectPlanCollection);
            }
            return list;
        }

		public IList<ObjectModel.ProjectPlanCollection> QueryByPage(Expression<Func<ObjectModel.ProjectPlanCollection, bool>> filter, string orderBy, int pageSize, int pageIndex, out int recordsCount)
        {         
            var newfilter = ExpressionConverter<ProjectPlanCollection>.Convert(filter);
			var dao = new ProjectPlanCollectionRepository();
            var dataList = dao.QueryByPage(newfilter, orderBy, pageSize, pageIndex, out recordsCount).ToList();           
            if (null == dataList) return null;
            var list = new List<ObjectModel.ProjectPlanCollection>();
            var rmodel = new ConvertModel();
            foreach (var vartemp in dataList)
            {
                var omProjectPlanCollection = rmodel.ReturnModel<ObjectModel.ProjectPlanCollection, ProjectPlanCollection>(vartemp);
                list.Add(omProjectPlanCollection);
            }
            return list;

        }
		public IList<ObjectModel.ProjectPlanCollection> GetProjectPlanCollectionFromCache()
        {
            var key = "ProjectPlanCollection_key";
			var query=CacheHelper.Get(key) as IList<ObjectModel.ProjectPlanCollection>;
            if (null == query)
            {
                query = this.Query(q => q.IsActive=="1");
				DateTime ExpirationTime = DateTime.Now.AddMinutes(ConstantManager.CacheCurrentUserExpirationTime);
                CacheHelper.Insert(key, query, ExpirationTime);
            }
            return query;
        }
		public ObjectModel.ProjectPlanCollection GetSingleOrDefault(Expression<Func<ObjectModel.ProjectPlanCollection, bool>> filter, string orderBy)
        {
            var newfilter = ExpressionConverter<ProjectPlanCollection>.Convert(filter);
            var dao = new ProjectPlanCollectionRepository();
            int recordCount = 0;
            var data = dao.QueryByPage(newfilter, orderBy, 1, 1, out recordCount).ToList().FirstOrDefault();
            if (null == data) return null;
            var list = new List<ObjectModel.ProjectPlanCollection>();
            var rmodel = new ConvertModel();
            return rmodel.ReturnModel<ObjectModel.ProjectPlanCollection, ProjectPlanCollection>(data);

        }
        #endregion
    }
}



